Repository Toss-Pay-Clone/App, pull requests merged in 2024-02, with the labels that each got.

#2 [chore] 초기 개발 환경 세팅
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor-report.md
  .github/ISSUE_TEMPLATE/setting-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/tosscloneproject/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tosscloneproject/MainActivity.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Color.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Theme.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/tosscloneproject/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 환경설정

#4 chore: 퍼블리싱 이슈 템플릿 등록
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/publishing-report.md
Labels: 환경설정

#8 [Design/#5] 메인페이지 퍼블리싱
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/tosscloneproject/MainActivity.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/BottomNavigationBar.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container1.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container2.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container3.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container4.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container5.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container6.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container7.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/Container8.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/MainPageView.kt
  app/src/main/java/com/example/tosscloneproject/mainPage/TopBar.kt
  app/src/main/res/drawable/arrow_down.png
  app/src/main/res/drawable/arrow_right.png
  app/src/main/res/drawable/toss_logo.png
  app/src/main/res/drawable/toss_symbol.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
Labels: 퍼블리싱

#10 [design/#7] 온보딩 페이지 퍼블리싱
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/example/tosscloneproject/Login/Compose/Button.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/NumberInput.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/UserInput.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/OnBoarding.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/Page1.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/Page2.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/Page3.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Check.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Name.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Register.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/ResidentNumber.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Telecom.kt
  app/src/main/java/com/example/tosscloneproject/MainActivity.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Color.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Type.kt
  app/src/main/res/drawable/arrow_bottom.png
  app/src/main/res/drawable/clear.png
  app/src/main/res/drawable/message_image.png
  app/src/main/res/drawable/number_image.png
  app/src/main/res/drawable/private_image.png
Labels: 퍼블리싱

#12 [Design/#6] 송금 계좌/연락처 페이지 퍼블리싱
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tosscloneproject/Transfer/Compose/AccountListItem.kt
  app/src/main/java/com/example/tosscloneproject/Transfer/Compose/AccountListTitle.kt
  app/src/main/java/com/example/tosscloneproject/Transfer/Compose/ContactListItem.kt
  app/src/main/java/com/example/tosscloneproject/Transfer/Compose/InputBox.kt
  app/src/main/java/com/example/tosscloneproject/Transfer/Compose/SelectTransfer.kt
  app/src/main/java/com/example/tosscloneproject/Transfer/Compose/TransferHeader.kt
  app/src/main/java/com/example/tosscloneproject/Transfer/Page/TransferSelectPage.kt
  app/src/main/res/drawable/icon_hana.png
  app/src/main/res/drawable/icon_kb.png
  app/src/main/res/drawable/icon_toss.png
  app/src/main/res/drawable/transfer_accountinfo_star_off.png
  app/src/main/res/drawable/transfer_accountinfo_star_on.png
  app/src/main/res/drawable/transfer_header_back.png
  app/src/main/res/drawable/transfer_input_search.png
Labels: 퍼블리싱, 기능구현

#15 [design/#11] 로그인 페이지 퍼블리싱 및 네비게이션 기능 추가
  app/src/main/java/com/example/tosscloneproject/Login/Compose/Animation.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/Button.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/InputDots.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/NumberBoard.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/NumberButton.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/NumberInput.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/UserInput.kt
  app/src/main/java/com/example/tosscloneproject/Login/Compose/ViewModel.kt
  app/src/main/java/com/example/tosscloneproject/Login/Login/Login.kt
  app/src/main/java/com/example/tosscloneproject/Login/Login/Success.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/OnBoarding.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/Page1.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/Page2.kt
  app/src/main/java/com/example/tosscloneproject/Login/OnBoarding/Page3.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Check.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Name.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Register.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/ResidentNumber.kt
  app/src/main/java/com/example/tosscloneproject/Login/Register/Telecom.kt
  app/src/main/java/com/example/tosscloneproject/MainActivity.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Color.kt
  app/src/main/java/com/example/tosscloneproject/ui/theme/Type.kt
  app/src/main/res/drawable/arrow_back.png
  app/src/main/res/drawable/graphicon.png
Labels: 퍼블리싱
